#!/bin/bash
#SERVERS=("sheep2:8081" "sheep3:8081" "sheep4:8081")
SERVERS=("localhsot:8081" "localhost:8082" "localhost:8083")

# $1 the serial number
# $2 is the keyname
# $3 is the number of required key, default is 1
function detect_url(){
    let k=$1%${#SERVERS[@]}
    #echo "d=$1, k=$k" 1>&2
    url="http://${SERVERS[$k]}/v1/keys/$2?number=${3:=1}"
    echo $url 1>&2
    result=$(curl -H "X-tans-token: 0BC9F3" -XPUT -s -i $url)
    if [ -z "$result" ]; then
	#echo "nothing"
	return 1
    fi

    if echo "$result"|grep 'HTTP/1.1 200 OK' >> /dev/null; then
	echo "$url"
    else
	loc=$(echo "$result"|grep 'location:')
	#echo "redirect to $loc"
	if [ -n "$loc" ]; then
	    head='location:'
	    s1=${loc##$head}
            s2=${s1%%&seq*}
            echo $s2
	fi
    fi    
}

REQ_COUNT=10000
PAR_COUNT=23
sleep_seconds=7

n=${1:-1000}

while [ true ]; do
    i=0
    army_no=$(date "+%M")
    army="army$army_no"

    epoch=$(date "+%s")
    let division_no=$epoch%1000+1
    division="division$division_no"

    while [ $i -lt $n ]; do
	let j=$i%200+1
	let num=$i%5+1
	url=$(detect_url $i "$army.$division.soldier$j.id" "$num")
	#echo $url
	if [ -n "$url" ]; then
	    #sleep 1
	    ab -q -S -n $REQ_COUNT -c $PAR_COUNT -k -l -m "PUT" -H "X-tans-token: 0BC9F3" "$url"
	fi
	let i=$i+1
	#echo $i
    done
    echo "sleep $sleep_seconds"
    sleep $sleep_seconds
done    
