#!/bin/bash
die () {
    echo
    echo "$*"
    echo
    exit 1
}

# Resolve links: $0 may be a link
PRG="$0"
# Need this for relative symlinks.
while [ -h "$PRG" ] ; do
    ls=`ls -ld "$PRG"`
    link=`expr "$ls" : '.*-> \(.*\)$'`
    if expr "$link" : '/.*' > /dev/null; then
        PRG="$link"
    else
        PRG=`dirname "$PRG"`"/$link"
    fi
done
SAVED="`pwd`"
cd "`dirname \"$PRG\"`/.." >/dev/null
APP_HOME="`pwd -P`"

# Determine the Java command to use to start the JVM.
if [ -n "$JAVA_HOME" ] ; then
    if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
        # IBM's JDK on AIX uses strange locations for the executables
        JAVACMD="$JAVA_HOME/jre/sh/java"
    else
        JAVACMD="$JAVA_HOME/bin/java"
    fi
    if [ ! -x "$JAVACMD" ] ; then
        die "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
    fi
else
    JAVACMD="java"
    which java >/dev/null 2>&1 || die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
fi

# Escape application args
save () {
    for i do printf %s\\n "$i" | sed "s/'/'\\\\''/g;1s/^/'/;\$s/\$/' \\\\/" ; done
    echo " "
}
APP_ARGS=$(save "$@")
DEFAULT_JVM_OPTS='"-server" "-Xmx128m" "-XX:+UseG1GC" "-XX:+AlwaysPreTouch" "-XX:InitiatingHeapOccupancyPercent=60"'

LIBS=("tans-netty-client-0.1" "netty-all-4.1.39.Final" "commons-cli-1.4" "commons-lang3-3.9" \
      "guava-27.0.1-jre" "logback-core-1.2.3" "logback-classic-1.2.3" "slf4j-api-1.7.25" \
      "failureaccess-1.0.1")

JAVA_OPTS="-classpath "
for lib in ${LIBS[*]}; do
    JAVA_OPTS="$JAVA_OPTS:./lib/$lib.jar"
done
MAIN_CLASS=org.axesoft.tans.client.ClientApp 
# Collect all arguments for the java command, following the shell quoting and substitution rules
eval set -- $DEFAULT_JVM_OPTS $JAVA_OPTS  $MAIN_CLASS "$APP_ARGS"

# by default we should be in the correct project dir, but when run from Finder on Mac, the cwd is wrong
if [ "$(uname)" = "Darwin" ] && [ "$HOME" = "$PWD" ]; then
  cd "$(dirname "$0")"
fi

exec "$JAVACMD" "$@"

cd "$SAVED" >/dev/null
